version: '3.7'

x-app-variables: &app-variables
  GRPC_PORT: ${GRPC_PORT:-6565}
  DB_HOST: ${DB_HOST:-db}
  DB_PORT: ${DB_PORT:-3306}
  DB_DATABASE: ${DB_DATABASE:-rotator}
  DB_PASSWORD: ${DB_PASSWORD:-secret}
  DB_USERNAME: ${DB_USERNAME:-root}
  AMQP_HOST: ${AMQP_HOST:-rabbitmq}
  AMQP_PORT: ${AMQP_PORT:-5672}
  AMQP_LOGIN: ${AMQP_LOGIN}
  AMQP_PASSWORD: ${AMQP_PASSWORD}
  AMQP_VHOST: ${AMQP_VHOST:-/}

services:
  app:
    build:
      context: ../
      dockerfile: ./build/package/Dockerfile
    depends_on:
      - "db"
    ports:
      - "${APP_GRPC_PORT-6565}:${APP_GRPC_PORT-6565}"
    environment: *app-variables
    command: ["wait-for", "-t", "60", "db:3306", "--", "wait-for", "-t", "60", "rabbitmq:5672", "--", "/app/bin/app"]
    networks:
      - internal
  db:
    image: mysql:5.7
    volumes:
      - ./db/data:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=${APP_DB_ROOT_PASSWORD:-secret}
      - MYSQL_DATABASE=${APP_DB_DATABASE:-rotator}
    networks:
      - internal
  rabbitmq:
    image: rabbitmq:3.8-alpine
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq:cached
      - ./rabbitmq/logs:/var/log/rabbitmq:cached
    networks:
      - internal
networks:
  internal:
    external: false